title: Jaya Narain
description: Sr. Research Scientist, Apple Health AI
url: "https://jn2810.github.io"
baseurl: ""

markdown: kramdown

sass:
  sass_dir: css
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
