###########
# site.url, site.title

title: 'Jaya Narain'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /jekyll-bootstrap-theme
url: 'http://jn2810.github.io'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

gems:
  - 'jekyll-scholar'
  - 'jekyll-paginate'
  - 'jekyll-gist'


exclude:
- README.md


safe: true
lsi: false

